import pandas as pd
from datetime import datetime

# === Load Excel ===
df = pd.read_excel("[Name of excel file]].xlsx")

# === Column mapping ===
df.rename(columns={
    "Product Code": "ProductNumber",
    "Product Description": "ProductDescription",
    "Department": "Dept",
    "Weighted Cost": "UnitCost"
}, inplace=True)

# === Constant values used in all MERGE scripts ===
today = datetime.now().strftime("%m/%d/%Y")

# === Function to produce MERGE script for each row ===
def generate_merge(row):
    return f"""
MERGE INTO CKSDeptProduct t
USING (
    SELECT 
        '{row.ProductNumber}' AS ProductNumber,
        '{row.Dept}' AS Dept,
        TO_DATE('{today}', 'MM/DD/YYYY') AS LISSDATE,
        0 AS RSTLVL,
        0 AS PSPRICE,
        ' ' AS TAXC,
        0 AS MAXLVL,
        TO_DATE('{today}', 'MM/DD/YYYY') AS LRCVDATE,
        0 AS CRTLVL,
        0 AS MINLVL,
        {row.UnitCost} AS UnitCost,
        0 AS STKLVL,
        0 AS BOPUC,
        0 AS BOPLVL,
        TO_DATE('{today}', 'MM/DD/YYYY') AS CDATE,
        ' ' AS CBY,
        TO_DATE('{today}', 'MM/DD/YYYY') AS LCDATE,
        ' ' AS LCBY,
        0 AS STATUS,
        0 AS DETACH,
        1 AS ISNEWADD,
        0 AS PRDID,
        0 AS CCISD,
        0 AS LPPRICE,
        ' ' AS LPSNUM,
        ' ' AS LPINUM,
        0 AS LPQTY,
        0 AS AUTOCNT,
        0 AS NOTCNT,
        0 AS QUOLNID,
        0 AS NIP,
        0 AS NXTQUOLNID,
        0 AS TYPE,
        '' AS GRP,
        '' AS DEPT,
        '{row.ProductNumberDESCR}' AS ProductNumberDESCR,
        ' ' AS STKSIZE,
        0 AS DELFLAG,
        ' ' AS PURGLC,
        ' ' AS INVGLC,
        ' ' AS SALGLC,
        ' ' AS BINNUM,
        ' ' AS HACCPTEMP,
        ' ' AS HACCPCERT,
        ' ' AS HACCPEXP,
        ' ' AS OVRSNUM,
        0 AS BOPVAL,
        0 AS SALCOSTGLC,
        ' ' AS ACCRUALGLC,
        0 AS IGNGLRULE,
        0 AS SALESDR,
        ' ' AS SALESCR,
        ' ' AS COGSDR,
        ' ' AS COGSCR,
        ' ' AS ACCRUALDR,
        ' ' AS ACCRUALCR,
        ' ' AS STCVARDR,
        ' ' AS STCVARCR,
        ' ' AS CLSINVDR,
        ' ' AS CLSINVCR,
        ' ' AS ADD1,
        ' ' AS ADD2,
        0 AS AMLNID,
        ' ' AS WOFDR,
        ' ' AS WOFCR,
        ' ' AS TRFIDR,
        ' ' AS TRFICR,
        ' ' AS TRFODR,
        ' ' AS TRFOCR,
        0 AS LTRIFROM,
        0 AS LTROTO,
        0 AS LLPPRICE,
        0 AS LLPQTY,
        0 AS LLPSNUM,
        0 AS LLPINUM,
        0 AS CONTAINER1,
        0 AS CONTAINER2,
        0 AS CONTAINER1CONV,
        0 AS CONTAINER2CONV,
        0 AS RECLC,
        0 AS SCOPEID,
        0 AS ENGSTCID,
        0 AS ENGCLOSELVL,
        0 AS ENGCLOSEVAL,
        0 AS ENGUnitCost,
        0 AS SLOWMOVING,
        0 AS LLTROTO,
        0 AS ACOGSDR,
        0 AS ACOGSCR,
        0 AS CALVARDR,
        0 AS CALVARCR,
        0 AS DTDept,
        TO_DATE('{today}', 'MM/DD/YYYY') AS STATUSSETON,
        ' ' AS PRODCODE,
        0 AS DEFAULTSIZE,
        0 AS DEPTDESCR,
        0 AS GRPDESCR,
        0 AS TYPEDESCR,
        0 AS STYPDESCR,
        0 AS STYP
    FROM dual
) s
ON (t.ProductNumber = s.ProductNumber AND t.Dept = s.Dept)
WHEN MATCHED THEN 
    UPDATE SET
        -- update all fields except PK
        t.RSTLVL = s.RSTLVL,
        t.PSPRICE = s.PSPRICE,
        t.TAXC = s.TAXC,
        t.MAXLVL = s.MAXLVL,
        t.LRCVDATE = s.LRCVDATE,
        t.CRTLVL = s.CRTLVL,
        t.MINLVL = s.MINLVL,
        t.UnitCost = s.UnitCost,
        t.STKLVL = s.STKLVL,
        t.BOPUC = s.BOPUC,
        t.BOPLVL = s.BOPLVL,
        t.CDATE = s.CDATE,
        t.CBY = s.CBY,
        t.LCDATE = s.LCDATE,
        t.LCBY = s.LCBY,
        t.STATUS = s.STATUS,
        t.DETACH = s.DETACH,
        t.ISNEWADD = s.ISNEWADD,
        t.PRDID = s.PRDID,
        t.CCISD = s.CCISD,
        t.LPPRICE = s.LPPRICE,
        t.LPSNUM = s.LPSNUM,
        t.LPINUM = s.LPINUM,
        t.LPQTY = s.LPQTY,
        t.AUTOCNT = s.AUTOCNT,
        t.NOTCNT = s.NOTCNT,
        t.QUOLNID = s.QUOLNID,
        t.NIP = s.NIP,
        t.NXTQUOLNID = s.NXTQUOLNID,
        t."TYPE" = s."TYPE",
        t.GRP = s.GRP,
        t.DEPT = s.DEPT,
        t.ProductNumberDESCR = s.ProductNumberDESCR,
        t.STKSIZE = s.STKSIZE,
        t.DELFLAG = s.DELFLAG,
        t.PURGLC = s.PURGLC,
        t.INVGLC = s.INVGLC,
        t.SALGLC = s.SALGLC,
        t.BINNUM = s.BINNUM,
        t.HACCPTEMP = s.HACCPTEMP,
        t.HACCPCERT = s.HACCPCERT,
        t.HACCPEXP = s.HACCPEXP,
        t.OVRSNUM = s.OVRSNUM,
        t.BOPVAL = s.BOPVAL,
        t.SALCOSTGLC = s.SALCOSTGLC,
        t.ACCRUALGLC = s.ACCRUALGLC,
        t.IGNGLRULE = s.IGNGLRULE,
        t.SALESDR = s.SALESDR,
        t.SALESCR = s.SALESCR,
        t.COGSDR = s.COGSDR,
        t.COGSCR = s.COGSCR,
        t.ACCRUALDR = s.ACCRUALDR,
        t.ACCRUALCR = s.ACCRUALCR,
        t.STCVARDR = s.STCVARDR,
        t.STCVARCR = s.STCVARCR,
        t.CLSINVDR = s.CLSINVDR,
        t.CLSINVCR = s.CLSINVCR,
        t.ADD1 = s.ADD1,
        t.ADD2 = s.ADD2,
        t.AMLNID = s.AMLNID,
        t.WOFDR = s.WOFDR,
        t.WOFCR = s.WOFCR,
        t.TRFIDR = s.TRFIDR,
        t.TRFICR = s.TRFICR,
        t.TRFODR = s.TRFODR,
        t.TRFOCR = s.TRFOCR,
        t.LTRIFROM = s.LTRIFROM,
        t.LTROTO = s.LTROTO,
        t.LLPPRICE = s.LLPPRICE,
        t.LLPQTY = s.LLPQTY,
        t.LLPSNUM = s.LLPSNUM,
        t.LLPINUM = s.LLPINUM,
        t.CONTAINER1 = s.CONTAINER1,
        t.CONTAINER2 = s.CONTAINER2,
        t.CONTAINER1CONV = s.CONTAINER1CONV,
        t.CONTAINER2CONV = s.CONTAINER2CONV,
        t.RECLC = s.RECLC,
        t.SCOPEID = s.SCOPEID,
        t.ENGSTCID = s.ENGSTCID,
        t.ENGCLOSELVL = s.ENGCLOSELVL,
        t.ENGCLOSEVAL = s.ENGCLOSEVAL,
        t.ENGUnitCost = s.ENGUnitCost,
        t.SLOWMOVING = s.SLOWMOVING,
        t.LLTROTO = s.LLTROTO,
        t.ACOGSDR = s.ACOGSDR,
        t.ACOGSCR = s.ACOGSCR,
        t.CALVARDR = s.CALVARDR,
        t.CALVARCR = s.CALVARCR,
        t.DTDept = s.DTDept,
        t.STATUSSETON = s.STATUSSETON,
        t.PRODCODE = s.PRODCODE,
        t.DEFAULTSIZE = s.DEFAULTSIZE,
        t.DEPTDESCR = s.DEPTDESCR,
        t.GRPDESCR = s.GRPDESCR,
        t.TYPEDESCR = s.TYPEDESCR,
        t.STYPDESCR = s.STYPDESCR,
        t.STYP = s.STYP
WHEN NOT MATCHED THEN
    INSERT (
        ProductNumber, Dept, LISSDATE, RSTLVL, PSPRICE, TAXC, MAXLVL,LRCVDATE,
        CRTLVL, MINLVL, UnitCost, STKLVL, BOPUC, BOPLVL, CDATE, CBY, LCDATE, LCBY,
        STATUS, DETACH, ISNEWADD, PRDID, CCISD, LPPRICE, LPSNUM, LPINUM, LPQTY,
        AUTOCNT, NOTCNT, QUOLNID, NIP, NXTQUOLNID, "TYPE", GRP, DEPT, ProductNumberDESCR,
        STKSIZE, DELFLAG, PURGLC, INVGLC, SALGLC, BINNUM, HACCPTEMP, HACCPCERT,
        HACCPEXP, OVRSNUM, BOPVAL, SALCOSTGLC, ACCRUALGLC, IGNGLRULE, SALESDR,
        SALESCR, COGSDR, COGSCR, ACCRUALDR, ACCRUALCR, STCVARDR, STCVARCR,
        CLSINVDR, CLSINVCR, ADD1, ADD2, AMLNID, WOFDR, WOFCR, TRFIDR, TRFICR,
        TRFODR, TRFOCR, LTRIFROM, LTROTO, LLPPRICE, LLPQTY, LLPSNUM, LLPINUM,
        CONTAINER1, CONTAINER2, CONTAINER1CONV, CONTAINER2CONV, RECLC, SCOPEID,
        ENGSTCID, ENGCLOSELVL, ENGCLOSEVAL, ENGUnitCost, SLOWMOVING, LLTROTO,
        ACOGSDR, ACOGSCR, CALVARDR, CALVARCR, DTDept, STATUSSETON, PRODCODE,
        DEFAULTSIZE, DEPTDESCR, GRPDESCR, TYPEDESCR, STYPDESCR, STYP
    ) VALUES (
        s.ProductNumber, s.Dept, s.LISSDATE, s.RSTLVL, s.PSPRICE, s.TAXC, s.MAXLVL,
        s.LRCVDATE, s.CRTLVL, s.MINLVL, s.UnitCost, s.STKLVL, s.BOPUC, s.BOPLVL,
        s.CDATE, s.CBY, s.LCDATE, s.LCBY, s.STATUS, s.DETACH, s.ISNEWADD,
        s.PRDID, s.CCISD, s.LPPRICE, s.LPSNUM, s.LPINUM, s.LPQTY, s.AUTOCNT,
        s.NOTCNT, s.QUOLNID, s.NIP, s.NXTQUOLNID, s."TYPE", s.GRP, s.DEPT,
        s.ProductNumberDESCR, s.STKSIZE, s.DELFLAG, s.PURGLC, s.INVGLC, s.SALGLC,
        s.BINNUM, s.HACCPTEMP, s.HACCPCERT, s.HACCPEXP, s.OVRSNUM, s.BOPVAL,
        s.SALCOSTGLC, s.ACCRUALGLC, s.IGNGLRULE, s.SALESDR, s.SALESCR, s.COGSDR,
        s.COGSCR, s.ACCRUALDR, s.ACCRUALCR, s.STCVARDR, s.STCVARCR, s.CLSINVDR,
        s.CLSINVCR, s.ADD1, s.ADD2, s.AMLNID, s.WOFDR, s.WOFCR, s.TRFIDR,
        s.TRFICR, s.TRFODR, s.TRFOCR, s.LTRIFROM, s.LTROTO, s.LLPPRICE,
        s.LLPQTY, s.LLPSNUM, s.LLPINUM, s.CONTAINER1, s.CONTAINER2,
        s.CONTAINER1CONV, s.CONTAINER2CONV, s.RECLC, s.SCOPEID, s.ENGSTCID,
        s.ENGCLOSELVL, s.ENGCLOSEVAL, s.ENGUnitCost, s.SLOWMOVING, s.LLTROTO,
        s.ACOGSDR, s.ACOGSCR, s.CALVARDR, s.CALVARCR, s.DTDept, s.STATUSSETON,
        s.PRODCODE, s.DEFAULTSIZE, s.DEPTDESCR, s.GRPDESCR, s.TYPEDESCR,
        s.STYPDESCR, s.STYP
    );
"""

# === Generate all scripts ===
sql_output = "\n".join(df.apply(generate_merge, axis=1))

# === Save to file ===
with open("MERGE_OUTPUT.sql", "w", encoding="utf-8") as f:
    f.write(sql_output)

print("MERGE scripts generated → MERGE_OUTPUT.sql")
